.TH "brlapi_authClientPacket_t" 3 "Fri Feb 22 2019" "Version 0.7" "BrlAPI" \" -*- nroff -*-
.ad l
.nh
.SH NAME
brlapi_authClientPacket_t
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <brlapi_protocol\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "uint32_t \fBtype\fP"
.br
.ti -1c
.RI "unsigned char \fBkey\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Structure of authorization packets 
.SH "Field Documentation"
.PP 
.SS "unsigned char brlapi_authClientPacket_t::key"

.SS "uint32_t brlapi_authClientPacket_t::type"


.SH "Author"
.PP 
Generated automatically by Doxygen for BrlAPI from the source code\&.
