.TH "brlapi_writeArguments_t" 3 "Fri Feb 22 2019" "Version 0.7" "BrlAPI" \" -*- nroff -*-
.ad l
.nh
.SH NAME
brlapi_writeArguments_t
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <brlapi\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "int \fBdisplayNumber\fP"
.br
.ti -1c
.RI "unsigned int \fBregionBegin\fP"
.br
.ti -1c
.RI "unsigned int \fBregionSize\fP"
.br
.ti -1c
.RI "char * \fBtext\fP"
.br
.ti -1c
.RI "int \fBtextSize\fP"
.br
.ti -1c
.RI "unsigned char * \fBandMask\fP"
.br
.ti -1c
.RI "unsigned char * \fBorMask\fP"
.br
.ti -1c
.RI "int \fBcursor\fP"
.br
.ti -1c
.RI "char * \fBcharset\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Structure containing arguments to be given to \fBbrlapi_write()\fP 
.SH "Field Documentation"
.PP 
.SS "unsigned char* brlapi_writeArguments_t::andMask"
And attributes; applied first 
.SS "char* brlapi_writeArguments_t::charset"
Text charset\&. NULL means it is assumed to be 8bits, and the same as the server's\&. '' means current locale's charset\&. If no locale was selected, defaults to NULL's meaning\&. 
.SS "int brlapi_writeArguments_t::cursor"
\fBBRLAPI_CURSOR_LEAVE\fP == don't touch, \fBBRLAPI_CURSOR_OFF\fP == turn off, 1 = 1st char of display, \&.\&.\&. 
.SS "int brlapi_writeArguments_t::displayNumber"
Display number \fBBRLAPI_DISPLAY_DEFAULT\fP == unspecified 
.SS "unsigned char* brlapi_writeArguments_t::orMask"
Or attributes; applied \fIafter\fP ANDing 
.SS "unsigned int brlapi_writeArguments_t::regionBegin"
Region of display to update, 1st character of display is 1 
.SS "unsigned int brlapi_writeArguments_t::regionSize"
Number of characters held in text, andMask and orMask\&. 
.SS "char* brlapi_writeArguments_t::text"
Text to display, must hold as many characters as the region fields expresses\&. 
.SS "int brlapi_writeArguments_t::textSize"
Size of text in bytes\&. If -1, strlen() is used for computing it\&. 

.SH "Author"
.PP 
Generated automatically by Doxygen for BrlAPI from the source code\&.
