.TH "brlapi_writeStruct" 3 "Fri Feb 22 2019" "Version 0.7" "BrlAPI" \" -*- nroff -*-
.ad l
.nh
.SH NAME
brlapi_writeStruct
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <brlapi\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "int \fBdisplayNumber\fP"
.br
.ti -1c
.RI "unsigned int \fBregionBegin\fP"
.br
.ti -1c
.RI "unsigned int \fBregionSize\fP"
.br
.ti -1c
.RI "char * \fBtext\fP"
.br
.ti -1c
.RI "int \fBtextSize\fP"
.br
.ti -1c
.RI "unsigned char * \fBattrAnd\fP"
.br
.ti -1c
.RI "unsigned char * \fBattrOr\fP"
.br
.ti -1c
.RI "int \fBcursor\fP"
.br
.ti -1c
.RI "char * \fBcharset\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
\fBbrlapi_writeStruct\fP, replaced by \fBbrlapi_writeArguments_t\fP 
.SH "Field Documentation"
.PP 
.SS "unsigned char* brlapi_writeStruct::attrAnd"

.SS "unsigned char* brlapi_writeStruct::attrOr"

.SS "char* brlapi_writeStruct::charset"

.SS "int brlapi_writeStruct::cursor"

.SS "int brlapi_writeStruct::displayNumber"

.SS "unsigned int brlapi_writeStruct::regionBegin"

.SS "unsigned int brlapi_writeStruct::regionSize"

.SS "char* brlapi_writeStruct::text"

.SS "int brlapi_writeStruct::textSize"


.SH "Author"
.PP 
Generated automatically by Doxygen for BrlAPI from the source code\&.
