.TH "brlapi_deprecated" 3 "Fri Feb 22 2019" "Version 0.7" "BrlAPI" \" -*- nroff -*-
.ad l
.nh
.SH NAME
brlapi_deprecated
.SH SYNOPSIS
.br
.PP
.SS "Data Structures"

.in +1c
.ti -1c
.RI "struct \fBbrlapi_writeStruct\fP"
.br
.in -1c
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBbrlapi_settings_t\fP   \fBbrlapi_connectionSettings_t\fP"
.br
.ti -1c
.RI "#define \fBBRLAPI_WRITESTRUCT_INITIALIZER\fP   \fBBRLAPI_WRITEARGUMENTS_INITIALIZER\fP"
.br
.ti -1c
.RI "#define \fBbrl_keycode_t\fP   \fBbrlapi_keyCode_t\fP"
.br
.ti -1c
.RI "#define \fBbrl_type_t\fP   \fBbrlapi_packetType_t\fP"
.br
.ti -1c
.RI "#define \fBBRLCOMMANDS\fP   NULL"
.br
.ti -1c
.RI "#define \fBBRL_KEYCODE_MAX\fP   \fBBRLAPI_KEY_MAX\fP"
.br
.ti -1c
.RI "#define \fBbrlapi_initializeConnection\fP   \fBbrlapi_openConnection\fP"
.br
.ti -1c
.RI "#define \fBbrlapi_getTty\fP   \fBbrlapi_enterTtyMode\fP"
.br
.ti -1c
.RI "#define \fBbrlapi_getTtyPath\fP   \fBbrlapi_enterTtyModeWithPath\fP"
.br
.ti -1c
.RI "#define \fBbrlapi_leaveTty\fP   \fBbrlapi_leaveTtyMode\fP"
.br
.ti -1c
.RI "#define \fBbrlapi_unignoreKeyRange\fP   brlapi_acceptKeyRange"
.br
.ti -1c
.RI "#define \fBbrlapi_unignoreKeySet\fP   brlapi_acceptKeySet"
.br
.ti -1c
.RI "#define \fBbrlapi_getRaw\fP   \fBbrlapi_enterRawMode\fP"
.br
.ti -1c
.RI "#define \fBbrlapi_leaveRaw\fP   \fBbrlapi_leaveRawMode\fP"
.br
.ti -1c
.RI "#define \fBbrlapi_suspend\fP   \fBbrlapi_suspendDriver\fP"
.br
.ti -1c
.RI "#define \fBbrlapi_resume\fP   \fBbrlapi_resumeDriver\fP"
.br
.ti -1c
.RI "#define \fBBRLERR_SUCCESS\fP   \fBBRLAPI_ERROR_SUCCESS\fP"
.br
.ti -1c
.RI "#define \fBBRLERR_NOMEM\fP   \fBBRLAPI_ERROR_NOMEM\fP"
.br
.ti -1c
.RI "#define \fBBRLERR_TTYBUSY\fP   \fBBRLAPI_ERROR_TTYBUSY\fP"
.br
.ti -1c
.RI "#define \fBBRLERR_DEVICEBUSY\fP   \fBBRLAPI_ERROR_DEVICEBUSY\fP"
.br
.ti -1c
.RI "#define \fBBRLERR_UNKNOWN_INSTRUCTION\fP   \fBBRLAPI_ERROR_UNKNOWN_INSTRUCTION\fP"
.br
.ti -1c
.RI "#define \fBBRLERR_ILLEGAL_INSTRUCTION\fP   \fBBRLAPI_ERROR_ILLEGAL_INSTRUCTION\fP"
.br
.ti -1c
.RI "#define \fBBRLERR_INVALID_PARAMETER\fP   \fBBRLAPI_ERROR_INVALID_PARAMETER\fP"
.br
.ti -1c
.RI "#define \fBBRLERR_INVALID_PACKET\fP   \fBBRLAPI_ERROR_INVALID_PACKET\fP"
.br
.ti -1c
.RI "#define \fBBRLERR_CONNREFUSED\fP   \fBBRLAPI_ERROR_CONNREFUSED\fP"
.br
.ti -1c
.RI "#define \fBBRLERR_OPNOTSUPP\fP   \fBBRLAPI_ERROR_OPNOTSUPP\fP"
.br
.ti -1c
.RI "#define \fBBRLERR_GAIERR\fP   \fBBRLAPI_ERROR_GAIERR\fP"
.br
.ti -1c
.RI "#define \fBBRLERR_LIBCERR\fP   \fBBRLAPI_ERROR_LIBCERR\fP"
.br
.ti -1c
.RI "#define \fBBRLERR_UNKNOWNTTY\fP   \fBBRLAPI_ERROR_UNKNOWNTTY\fP"
.br
.ti -1c
.RI "#define \fBBRLERR_PROTOCOL_VERSION\fP   \fBBRLAPI_ERROR_PROTOCOL_VERSION\fP"
.br
.ti -1c
.RI "#define \fBBRLERR_EOF\fP   \fBBRLAPI_ERROR_EOF\fP"
.br
.ti -1c
.RI "#define \fBBRLERR_EMPTYKEY\fP   \fBBRLAPI_ERROR_EMPTYKEY\fP"
.br
.ti -1c
.RI "#define \fBBRLERR_DRIVERERROR\fP   \fBBRLAPI_ERROR_DRIVERERROR\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
With version 0\&.5\&.0, BrlAPI is now provided through including <\fBbrlapi\&.h\fP> and got a big renaming pass\&. Old names are still available through macros, but they are deprecated since they will get dropped in the next release\&. This documentation is for you to know the new names\&.
.PP
For checking that you have completely switched to new names, just define BRLAPI_NO_DEPRECATED: that will disable compatibility macros\&. 
.SH "Macro Definition Documentation"
.PP 
.SS "#define BRL_KEYCODE_MAX   \fBBRLAPI_KEY_MAX\fP"

.SS "#define brl_keycode_t   \fBbrlapi_keyCode_t\fP"

.SS "#define brl_type_t   \fBbrlapi_packetType_t\fP"

.SS "#define brlapi_getRaw   \fBbrlapi_enterRawMode\fP"

.SS "#define brlapi_getTty   \fBbrlapi_enterTtyMode\fP"

.SS "#define brlapi_getTtyPath   \fBbrlapi_enterTtyModeWithPath\fP"

.SS "#define brlapi_initializeConnection   \fBbrlapi_openConnection\fP"

.SS "#define brlapi_leaveRaw   \fBbrlapi_leaveRawMode\fP"

.SS "#define brlapi_leaveTty   \fBbrlapi_leaveTtyMode\fP"

.SS "#define brlapi_resume   \fBbrlapi_resumeDriver\fP"

.SS "#define brlapi_settings_t   \fBbrlapi_connectionSettings_t\fP"

.SS "#define brlapi_suspend   \fBbrlapi_suspendDriver\fP"

.SS "#define brlapi_unignoreKeyRange   brlapi_acceptKeyRange"

.SS "#define brlapi_unignoreKeySet   brlapi_acceptKeySet"

.SS "#define BRLAPI_WRITESTRUCT_INITIALIZER   \fBBRLAPI_WRITEARGUMENTS_INITIALIZER\fP"

.SS "#define BRLCOMMANDS   NULL"

.SS "#define BRLERR_CONNREFUSED   \fBBRLAPI_ERROR_CONNREFUSED\fP"

.SS "#define BRLERR_DEVICEBUSY   \fBBRLAPI_ERROR_DEVICEBUSY\fP"

.SS "#define BRLERR_DRIVERERROR   \fBBRLAPI_ERROR_DRIVERERROR\fP"

.SS "#define BRLERR_EMPTYKEY   \fBBRLAPI_ERROR_EMPTYKEY\fP"

.SS "#define BRLERR_EOF   \fBBRLAPI_ERROR_EOF\fP"

.SS "#define BRLERR_GAIERR   \fBBRLAPI_ERROR_GAIERR\fP"

.SS "#define BRLERR_ILLEGAL_INSTRUCTION   \fBBRLAPI_ERROR_ILLEGAL_INSTRUCTION\fP"

.SS "#define BRLERR_INVALID_PACKET   \fBBRLAPI_ERROR_INVALID_PACKET\fP"

.SS "#define BRLERR_INVALID_PARAMETER   \fBBRLAPI_ERROR_INVALID_PARAMETER\fP"

.SS "#define BRLERR_LIBCERR   \fBBRLAPI_ERROR_LIBCERR\fP"

.SS "#define BRLERR_NOMEM   \fBBRLAPI_ERROR_NOMEM\fP"

.SS "#define BRLERR_OPNOTSUPP   \fBBRLAPI_ERROR_OPNOTSUPP\fP"

.SS "#define BRLERR_PROTOCOL_VERSION   \fBBRLAPI_ERROR_PROTOCOL_VERSION\fP"

.SS "#define BRLERR_SUCCESS   \fBBRLAPI_ERROR_SUCCESS\fP"

.SS "#define BRLERR_TTYBUSY   \fBBRLAPI_ERROR_TTYBUSY\fP"

.SS "#define BRLERR_UNKNOWN_INSTRUCTION   \fBBRLAPI_ERROR_UNKNOWN_INSTRUCTION\fP"

.SS "#define BRLERR_UNKNOWNTTY   \fBBRLAPI_ERROR_UNKNOWNTTY\fP"

.SH "Author"
.PP 
Generated automatically by Doxygen for BrlAPI from the source code\&.
