.TH "brlapi_version" 3 "Fri Feb 22 2019" "Version 0.7" "BrlAPI" \" -*- nroff -*-
.ad l
.nh
.SH NAME
brlapi_version
.SH SYNOPSIS
.br
.PP
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBBRLAPI_RELEASE\fP   '0\&.7\&.0'"
.br
.ti -1c
.RI "#define \fBBRLAPI_MAJOR\fP   0"
.br
.ti -1c
.RI "#define \fBBRLAPI_MINOR\fP   7"
.br
.ti -1c
.RI "#define \fBBRLAPI_REVISION\fP   0"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBbrlapi_getLibraryVersion\fP (int *major, int *minor, int *revision)"
.br
.in -1c
.SH "Detailed Description"
.PP 

.SH "Macro Definition Documentation"
.PP 
.SS "#define BRLAPI_MAJOR   0"
Library major version\&. 
.SS "#define BRLAPI_MINOR   7"
Library minor version\&. 
.SS "#define BRLAPI_RELEASE   '0\&.7\&.0'"
Library version\&. 
.SS "#define BRLAPI_REVISION   0"
Library revision\&. 
.SH "Function Documentation"
.PP 
.SS "void brlapi_getLibraryVersion (int * major, int * minor, int * revision)"
Returns the version of the library 
.SH "Author"
.PP 
Generated automatically by Doxygen for BrlAPI from the source code\&.
