# Dependencies for screen.$O:
screen.$O: $(SRC_DIR)/screen.c
screen.$O: $(SRC_TOP)Headers/prologue.h
screen.$O: $(BLD_TOP)config.h
screen.$O: $(BLD_TOP)forbuild.h
screen.$O: $(SRC_TOP)Headers/log.h
screen.$O: $(BLD_TOP)Programs/brlapi_constants.h
screen.$O: $(SRC_TOP)Programs/brlapi_keycodes.h
screen.$O: $(SRC_TOP)Programs/brlapi_param.h
screen.$O: $(SRC_TOP)Programs/report.h
screen.$O: $(SRC_TOP)Headers/async.h
screen.$O: $(SRC_TOP)Headers/async_io.h
screen.$O: $(SRC_TOP)Headers/device.h
screen.$O: $(SRC_TOP)Headers/get_sockets.h
screen.$O: $(SRC_TOP)Headers/io_misc.h
screen.$O: $(SRC_TOP)Headers/timing.h
screen.$O: $(SRC_TOP)Headers/parse.h
screen.$O: $(SRC_TOP)Headers/brl_cmds.h
screen.$O: $(SRC_TOP)Headers/brl_dots.h
screen.$O: $(SRC_TOP)Headers/kbd_keycodes.h
screen.$O: $(SRC_TOP)Headers/ascii.h
screen.$O: $(SRC_TOP)Headers/unicode.h
screen.$O: $(SRC_TOP)Headers/charset.h
screen.$O: $(SRC_TOP)Headers/lock.h
screen.$O: $(SRC_TOP)Headers/utf8.h
screen.$O: $(SRC_TOP)Headers/driver.h
screen.$O: $(SRC_TOP)Headers/ktb_types.h
screen.$O: $(SRC_TOP)Headers/scr_base.h
screen.$O: $(SRC_TOP)Headers/scr_gpm.h
screen.$O: $(SRC_TOP)Headers/scr_main.h
screen.$O: $(SRC_TOP)Headers/scr_types.h
screen.$O: $(SRC_TOP)Headers/system_linux.h
screen.$O: $(SRC_TOP)Headers/scr_driver.h
screen.$O: $(SRC_TOP)Headers/scr_real.h
screen.$O: $(SRC_TOP)Headers/scr_utils.h
screen.$O: $(SRC_DIR)/screen.h

